openapi: 3.0.0
info:
  title: Quiz Game API
  version: 1.0.0
  description: API for creating and managing quiz games

paths:
  /quizzes:
    get:
      summary: Get all quizzes
      responses:
        '200':
          description: A list of quizzes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quiz'
    post:
      summary: Create a new quiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '201':
          description: Quiz created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'

  /quizzes/{quizId}:
    get:
      summary: Get a quiz by ID
      parameters:
        - name: quizId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A quiz object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
    put:
      summary: Update a quiz by ID
      parameters:
        - name: quizId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quiz'
      responses:
        '200':
          description: Quiz updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quiz'
    delete:
      summary: Delete a quiz by ID
      parameters:
        - name: quizId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Quiz deleted successfully

components:
  schemas:
    Quiz:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        questions:
          type: array
          items:
            $ref: '#/components/schemas/Question'

    Question:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
        correctOptionId:
          type: string

    Option:
      type: object
      properties:
        id:
          type: string
        text:
          type: string